-- migration_ctl DDL: MIGRATION_RUN / PHASE_STATUS / MIGRATION_OBJECT
-- 実行ユーザー: migration_ctl
-- 実行対象: oracle-tgt (localhost:1522/XEPDB1)

WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR  EXIT FAILURE
SET ECHO ON
SET FEEDBACK ON

-- ===========================================================================
-- MIGRATION_RUN（移行実行親テーブル）
-- ===========================================================================

CREATE SEQUENCE SEQ_MIGRATION_RUN
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE MIGRATION_RUN (
    MIG_RUN_ID        NUMBER(10)     NOT NULL,
    RUN_NAME          VARCHAR2(100)  NOT NULL,
    RUN_TYPE          VARCHAR2(20)   NOT NULL,
    STATUS            VARCHAR2(20)   DEFAULT 'CREATED' NOT NULL,
    BASELINE_SCN      NUMBER(20),
    MINING_START_SCN  NUMBER(20),
    STARTED_AT        TIMESTAMP,
    FINISHED_AT       TIMESTAMP,
    LOG_RUN_ID        NUMBER(10),
    REMARKS           VARCHAR2(4000),
    CREATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP,
    CONSTRAINT PK_MIGRATION_RUN
        PRIMARY KEY (MIG_RUN_ID),
    CONSTRAINT UQ_MIGRATION_RUN_NAME
        UNIQUE (RUN_NAME),
    CONSTRAINT CHK_MIG_RUN_TYPE
        CHECK (RUN_TYPE IN ('POC', 'REHEARSAL', 'PRODUCTION')),
    CONSTRAINT CHK_MIG_RUN_STATUS
        CHECK (STATUS IN ('CREATED', 'RUNNING', 'DONE', 'FAILED', 'ABORTED')),
    CONSTRAINT CHK_MIG_RUN_SCN
        CHECK (MINING_START_SCN IS NULL
               OR BASELINE_SCN IS NULL
               OR MINING_START_SCN <= BASELINE_SCN)
);

CREATE OR REPLACE TRIGGER TRG_MIGRATION_RUN_BI
BEFORE INSERT ON MIGRATION_RUN
FOR EACH ROW
BEGIN
    IF :NEW.MIG_RUN_ID IS NULL THEN
        SELECT SEQ_MIGRATION_RUN.NEXTVAL
        INTO :NEW.MIG_RUN_ID FROM DUAL;
    END IF;
END;
/

-- ===========================================================================
-- PHASE_STATUS（フェーズ進捗テーブル）
-- ===========================================================================

CREATE SEQUENCE SEQ_PHASE_STATUS
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE PHASE_STATUS (
    PHASE_STATUS_ID   NUMBER(10)     NOT NULL,
    MIG_RUN_ID        NUMBER(10)     NOT NULL,
    PHASE_CODE        VARCHAR2(20)   NOT NULL,
    STATUS            VARCHAR2(20)   DEFAULT 'NOT_STARTED' NOT NULL,
    STARTED_AT        TIMESTAMP,
    FINISHED_AT       TIMESTAMP,
    ERROR_MESSAGE     VARCHAR2(4000),
    REMARKS           VARCHAR2(4000),
    CREATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP,
    CONSTRAINT PK_PHASE_STATUS
        PRIMARY KEY (PHASE_STATUS_ID),
    CONSTRAINT FK_PHASE_STATUS_RUN
        FOREIGN KEY (MIG_RUN_ID)
        REFERENCES MIGRATION_RUN (MIG_RUN_ID),
    CONSTRAINT UQ_PHASE_STATUS_CODE
        UNIQUE (MIG_RUN_ID, PHASE_CODE),
    CONSTRAINT CHK_PHASE_STATUS_CODE
        CHECK (PHASE_CODE IN
               ('PREP_A', 'PREP_B', 'PHASE1', 'PHASE2', 'PHASE3', 'PHASE4', 'PHASE5')),
    CONSTRAINT CHK_PHASE_STATUS_STS
        CHECK (STATUS IN ('NOT_STARTED', 'RUNNING', 'DONE', 'FAILED'))
);

CREATE OR REPLACE TRIGGER TRG_PHASE_STATUS_BI
BEFORE INSERT ON PHASE_STATUS
FOR EACH ROW
BEGIN
    IF :NEW.PHASE_STATUS_ID IS NULL THEN
        SELECT SEQ_PHASE_STATUS.NEXTVAL
        INTO :NEW.PHASE_STATUS_ID FROM DUAL;
    END IF;
END;
/

-- ===========================================================================
-- MIGRATION_OBJECT（対象オブジェクト台帳）
-- ===========================================================================

CREATE SEQUENCE SEQ_MIGRATION_OBJECT
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE MIGRATION_OBJECT (
    MIG_OBJECT_ID          NUMBER(10)     NOT NULL,
    MIG_RUN_ID             NUMBER(10)     NOT NULL,
    OBJECT_SCHEMA          VARCHAR2(100)  NOT NULL,
    OBJECT_NAME            VARCHAR2(100)  NOT NULL,
    MIGRATION_METHOD       VARCHAR2(20)   NOT NULL,
    PROCESS_ORDER          NUMBER(5),
    EST_ROW_COUNT          NUMBER(20),
    EST_SIZE_MB            NUMBER(10,2),
    CDC_CATALOG_TABLE_NAME VARCHAR2(100),
    STATUS                 VARCHAR2(20)   DEFAULT 'PENDING' NOT NULL,
    REMARKS                VARCHAR2(4000),
    CREATED_AT             TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT             TIMESTAMP,
    CONSTRAINT PK_MIGRATION_OBJECT
        PRIMARY KEY (MIG_OBJECT_ID),
    CONSTRAINT FK_MIG_OBJECT_RUN
        FOREIGN KEY (MIG_RUN_ID)
        REFERENCES MIGRATION_RUN (MIG_RUN_ID),
    CONSTRAINT UQ_MIG_OBJECT_NAME
        UNIQUE (MIG_RUN_ID, OBJECT_SCHEMA, OBJECT_NAME),
    CONSTRAINT CHK_MIG_OBJECT_METHOD
        CHECK (MIGRATION_METHOD IN ('FULL', 'CDC', 'TRANSFORM', 'SKIP')),
    CONSTRAINT CHK_MIG_OBJECT_STATUS
        CHECK (STATUS IN ('PENDING', 'IN_PROGRESS', 'DONE', 'FAILED', 'SKIPPED'))
);

CREATE OR REPLACE TRIGGER TRG_MIGRATION_OBJECT_BI
BEFORE INSERT ON MIGRATION_OBJECT
FOR EACH ROW
BEGIN
    IF :NEW.MIG_OBJECT_ID IS NULL THEN
        SELECT SEQ_MIGRATION_OBJECT.NEXTVAL
        INTO :NEW.MIG_OBJECT_ID FROM DUAL;
    END IF;
END;
/

EXIT;
