-- migration_ctl DDL v2.0: 9テーブル全体再作成
-- 実行ユーザー: migration_ctl
-- 実行対象: oracle-tgt (localhost:1522/XEPDB1)
-- 設計書: docs/migration-control-schema-design.md v2.0

WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR  EXIT FAILURE
SET ECHO ON
SET FEEDBACK ON

-- ===========================================================================
-- 既存オブジェクトを安全にDROP（存在しない場合は無視）
-- TABLEをCASCADE CONSTRAINTSで先に落とし、次にSEQUENCEを落とす
-- TRIGGERはTABLE DROP時に自動削除されるため個別削除不要
-- ===========================================================================
BEGIN
  FOR obj IN (
    SELECT object_name, object_type
    FROM user_objects
    ORDER BY
      CASE object_type
        WHEN 'TABLE'    THEN 2
        WHEN 'SEQUENCE' THEN 1
        WHEN 'TRIGGER'  THEN 0
      END DESC,
      object_name
  ) LOOP
    BEGIN
      IF obj.object_type = 'TABLE' THEN
        EXECUTE IMMEDIATE
          'DROP TABLE ' || obj.object_name || ' CASCADE CONSTRAINTS';
      ELSIF obj.object_type = 'SEQUENCE' THEN
        EXECUTE IMMEDIATE
          'DROP SEQUENCE ' || obj.object_name;
      END IF;
    EXCEPTION WHEN OTHERS THEN NULL;
    END;
  END LOOP;
END;
/

-- ===========================================================================
-- 1. MIGRATION_RUN（移行実行親テーブル）
-- ===========================================================================

CREATE SEQUENCE SEQ_MIGRATION_RUN
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE MIGRATION_RUN (
    MIG_RUN_ID          NUMBER(10)     NOT NULL,
    RUN_NAME            VARCHAR2(100)  NOT NULL,
    RUN_TYPE            VARCHAR2(20)   NOT NULL,
    SOURCE_DB_INFO      VARCHAR2(500),
    TARGET_DB_INFO      VARCHAR2(500),
    STATUS              VARCHAR2(20)   DEFAULT 'CREATED' NOT NULL,
    BASELINE_SCN        NUMBER(20),
    BASELINE_FIXED_AT   TIMESTAMP,
    MINING_START_SCN    NUMBER(20),
    ARCHIVE_READY_AT    TIMESTAMP,
    TARGET_END_SCN      NUMBER(20),
    LAST_APPLIED_SCN    NUMBER(20),
    STARTED_AT          TIMESTAMP,
    FINISHED_AT         TIMESTAMP,
    LOG_RUN_ID          NUMBER(10),
    REMARKS             VARCHAR2(4000),
    CREATED_AT          TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP,
    CONSTRAINT PK_MIGRATION_RUN
        PRIMARY KEY (MIG_RUN_ID),
    CONSTRAINT UQ_MIGRATION_RUN_NAME
        UNIQUE (RUN_NAME),
    CONSTRAINT CHK_MIG_RUN_TYPE
        CHECK (RUN_TYPE IN ('POC', 'REHEARSAL', 'PRODUCTION')),
    CONSTRAINT CHK_MIG_RUN_STATUS
        CHECK (STATUS IN (
            'CREATED', 'ARCHIVE_READY', 'BASELINE_FIXED',
            'EXPORTING', 'IMPORTING', 'RUNNING',
            'COMPLETED', 'FAILED', 'ABORTED')),
    CONSTRAINT CHK_MIG_RUN_SCN
        CHECK (MINING_START_SCN IS NULL
               OR BASELINE_SCN IS NULL
               OR MINING_START_SCN <= BASELINE_SCN)
);

CREATE OR REPLACE TRIGGER TRG_MIGRATION_RUN_BI
BEFORE INSERT ON MIGRATION_RUN
FOR EACH ROW
BEGIN
    IF :NEW.MIG_RUN_ID IS NULL THEN
        SELECT SEQ_MIGRATION_RUN.NEXTVAL
        INTO :NEW.MIG_RUN_ID FROM DUAL;
    END IF;
END;
/

-- ===========================================================================
-- 2. PHASE_STATUS（フェーズ進捗テーブル）FK→MIGRATION_RUN
-- ===========================================================================

CREATE SEQUENCE SEQ_PHASE_STATUS
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE PHASE_STATUS (
    PHASE_STATUS_ID  NUMBER(10)     NOT NULL,
    MIG_RUN_ID       NUMBER(10)     NOT NULL,
    PHASE_CODE       VARCHAR2(20)   NOT NULL,
    STATUS           VARCHAR2(20)   DEFAULT 'NOT_STARTED' NOT NULL,
    STARTED_AT       TIMESTAMP,
    FINISHED_AT      TIMESTAMP,
    ERROR_MESSAGE    VARCHAR2(4000),
    REMARKS          VARCHAR2(4000),
    CREATED_AT       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT       TIMESTAMP,
    CONSTRAINT PK_PHASE_STATUS
        PRIMARY KEY (PHASE_STATUS_ID),
    CONSTRAINT FK_PHASE_STATUS_RUN
        FOREIGN KEY (MIG_RUN_ID)
        REFERENCES MIGRATION_RUN (MIG_RUN_ID),
    CONSTRAINT UQ_PHASE_STATUS_CODE
        UNIQUE (MIG_RUN_ID, PHASE_CODE),
    CONSTRAINT CHK_PHASE_STATUS_CODE
        CHECK (PHASE_CODE IN
               ('PREP_A','PREP_B','PHASE1','PHASE2',
                'PHASE3','PHASE4','PHASE5')),
    CONSTRAINT CHK_PHASE_STATUS_STS
        CHECK (STATUS IN
               ('NOT_STARTED','RUNNING','COMPLETED','FAILED','PAUSED'))
);

CREATE OR REPLACE TRIGGER TRG_PHASE_STATUS_BI
BEFORE INSERT ON PHASE_STATUS
FOR EACH ROW
BEGIN
    IF :NEW.PHASE_STATUS_ID IS NULL THEN
        SELECT SEQ_PHASE_STATUS.NEXTVAL
        INTO :NEW.PHASE_STATUS_ID FROM DUAL;
    END IF;
END;
/

-- ===========================================================================
-- 3. MIGRATION_OBJECT（対象オブジェクト台帳）FK→MIGRATION_RUN
-- ===========================================================================

CREATE SEQUENCE SEQ_MIGRATION_OBJECT
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE MIGRATION_OBJECT (
    MIG_OBJECT_ID         NUMBER(10)     NOT NULL,
    MIG_RUN_ID            NUMBER(10)     NOT NULL,
    SOURCE_OWNER          VARCHAR2(100)  NOT NULL,
    SOURCE_TABLE_NAME     VARCHAR2(100)  NOT NULL,
    STAGE_OWNER           VARCHAR2(100),
    STAGE_TABLE_NAME      VARCHAR2(100),
    TARGET_OWNER          VARCHAR2(100),
    TARGET_TABLE_NAME     VARCHAR2(100),
    FULL_LOAD_FLAG        CHAR(1)        DEFAULT 'Y' NOT NULL,
    CDC_FLAG              CHAR(1)        DEFAULT 'N' NOT NULL,
    TRANSFORM_FLAG        CHAR(1)        DEFAULT 'N' NOT NULL,
    PRIMARY_KEY_COLUMNS   VARCHAR2(1000),
    HAS_LOB_FLAG          CHAR(1)        DEFAULT 'N' NOT NULL,
    ESTIMATED_ROWS        NUMBER(20),
    ESTIMATED_DATA_BYTES  NUMBER(20),
    ESTIMATED_LOB_BYTES   NUMBER(20),
    EXPORT_GROUP_CODE     VARCHAR2(100),
    APPLY_ORDER_NO        NUMBER(5),
    TRANSFORM_ORDER_NO    NUMBER(5),
    STATUS                VARCHAR2(20)   DEFAULT 'PENDING' NOT NULL,
    REMARKS               VARCHAR2(4000),
    CREATED_AT            TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT            TIMESTAMP,
    CONSTRAINT PK_MIGRATION_OBJECT
        PRIMARY KEY (MIG_OBJECT_ID),
    CONSTRAINT FK_MIG_OBJECT_RUN
        FOREIGN KEY (MIG_RUN_ID)
        REFERENCES MIGRATION_RUN (MIG_RUN_ID),
    CONSTRAINT UQ_MIG_OBJECT_SRC
        UNIQUE (MIG_RUN_ID, SOURCE_OWNER, SOURCE_TABLE_NAME),
    CONSTRAINT CHK_MIG_OBJ_STATUS
        CHECK (STATUS IN
               ('PENDING','IN_PROGRESS','COMPLETED','FAILED','SKIPPED')),
    CONSTRAINT CHK_MIG_OBJ_FL_FLAG
        CHECK (FULL_LOAD_FLAG IN ('Y','N')),
    CONSTRAINT CHK_MIG_OBJ_CDC_FLAG
        CHECK (CDC_FLAG IN ('Y','N')),
    CONSTRAINT CHK_MIG_OBJ_TRF_FLAG
        CHECK (TRANSFORM_FLAG IN ('Y','N')),
    CONSTRAINT CHK_MIG_OBJ_LOB_FLAG
        CHECK (HAS_LOB_FLAG IN ('Y','N'))
);

CREATE OR REPLACE TRIGGER TRG_MIGRATION_OBJECT_BI
BEFORE INSERT ON MIGRATION_OBJECT
FOR EACH ROW
BEGIN
    IF :NEW.MIG_OBJECT_ID IS NULL THEN
        SELECT SEQ_MIGRATION_OBJECT.NEXTVAL
        INTO :NEW.MIG_OBJECT_ID FROM DUAL;
    END IF;
END;
/

-- ===========================================================================
-- 4. DATAPUMP_JOB（Data Pump ジョブ管理テーブル）FK→MIGRATION_RUN
-- ===========================================================================

CREATE SEQUENCE SEQ_DATAPUMP_JOB
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE DATAPUMP_JOB (
    DATAPUMP_JOB_ID  NUMBER(10)     NOT NULL,
    MIG_RUN_ID       NUMBER(10)     NOT NULL,
    JOB_NAME         VARCHAR2(128)  NOT NULL,
    OPERATION        VARCHAR2(20)   NOT NULL,
    STATUS           VARCHAR2(20)   DEFAULT 'PLANNED' NOT NULL,
    BASELINE_SCN     NUMBER(20),
    PARALLEL         NUMBER(5),
    DIRECTORY_NAME   VARCHAR2(128),
    LOG_FILE_NAME    VARCHAR2(500),
    ORACLE_JOB_NAME  VARCHAR2(128),
    EXECUTE_HOST     VARCHAR2(200),
    EXECUTE_INSTANCE VARCHAR2(200),
    STARTED_AT       TIMESTAMP,
    FINISHED_AT      TIMESTAMP,
    PROCESSED_ROWS   NUMBER(20),
    PROCESSED_BYTES  NUMBER(20),
    ERROR_COUNT      NUMBER(10),
    REMARKS          VARCHAR2(4000),
    CREATED_AT       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT       TIMESTAMP,
    CONSTRAINT PK_DATAPUMP_JOB
        PRIMARY KEY (DATAPUMP_JOB_ID),
    CONSTRAINT FK_DATAPUMP_JOB_RUN
        FOREIGN KEY (MIG_RUN_ID)
        REFERENCES MIGRATION_RUN (MIG_RUN_ID),
    CONSTRAINT CHK_DATAPUMP_JOB_OP
        CHECK (OPERATION IN ('EXPORT','IMPORT','SQLFILE')),
    CONSTRAINT CHK_DATAPUMP_JOB_STS
        CHECK (STATUS IN
               ('PLANNED','RUNNING','COMPLETED','FAILED','RETRY'))
);

CREATE OR REPLACE TRIGGER TRG_DATAPUMP_JOB_BI
BEFORE INSERT ON DATAPUMP_JOB
FOR EACH ROW
BEGIN
    IF :NEW.DATAPUMP_JOB_ID IS NULL THEN
        SELECT SEQ_DATAPUMP_JOB.NEXTVAL
        INTO :NEW.DATAPUMP_JOB_ID FROM DUAL;
    END IF;
END;
/

-- ===========================================================================
-- 5. DATAPUMP_JOB_OBJECT（ジョブ×対象テーブル対応）
--    FK→DATAPUMP_JOB, FK→MIGRATION_OBJECT
-- ===========================================================================

CREATE SEQUENCE SEQ_DATAPUMP_JOB_OBJECT
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE DATAPUMP_JOB_OBJECT (
    DP_JOB_OBJECT_ID  NUMBER(10)     NOT NULL,
    DATAPUMP_JOB_ID   NUMBER(10)     NOT NULL,
    MIG_OBJECT_ID     NUMBER(10)     NOT NULL,
    STATUS            VARCHAR2(20)   DEFAULT 'PLANNED' NOT NULL,
    PROCESSED_ROWS    NUMBER(20),
    CREATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP,
    CONSTRAINT PK_DATAPUMP_JOB_OBJECT
        PRIMARY KEY (DP_JOB_OBJECT_ID),
    CONSTRAINT FK_DP_JOB_OBJ_JOB
        FOREIGN KEY (DATAPUMP_JOB_ID)
        REFERENCES DATAPUMP_JOB (DATAPUMP_JOB_ID),
    CONSTRAINT FK_DP_JOB_OBJ_MIG_OBJ
        FOREIGN KEY (MIG_OBJECT_ID)
        REFERENCES MIGRATION_OBJECT (MIG_OBJECT_ID),
    CONSTRAINT UQ_DP_JOB_OBJECT
        UNIQUE (DATAPUMP_JOB_ID, MIG_OBJECT_ID),
    CONSTRAINT CHK_DP_JOB_OBJ_STATUS
        CHECK (STATUS IN
               ('PLANNED','RUNNING','COMPLETED','FAILED','SKIPPED'))
);

CREATE OR REPLACE TRIGGER TRG_DP_JOB_OBJECT_BI
BEFORE INSERT ON DATAPUMP_JOB_OBJECT
FOR EACH ROW
BEGIN
    IF :NEW.DP_JOB_OBJECT_ID IS NULL THEN
        SELECT SEQ_DATAPUMP_JOB_OBJECT.NEXTVAL
        INTO :NEW.DP_JOB_OBJECT_ID FROM DUAL;
    END IF;
END;
/

-- ===========================================================================
-- 6. DATAPUMP_FILE（ダンプ・ログ・関連ファイル管理テーブル）
--    FK→MIGRATION_RUN, FK→DATAPUMP_JOB（nullable）
-- ===========================================================================

CREATE SEQUENCE SEQ_DATAPUMP_FILE
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE DATAPUMP_FILE (
    DATAPUMP_FILE_ID   NUMBER(10)     NOT NULL,
    MIG_RUN_ID         NUMBER(10)     NOT NULL,
    DATAPUMP_JOB_ID    NUMBER(10),
    FILE_ROLE          VARCHAR2(20)   NOT NULL,
    STATUS             VARCHAR2(20)   DEFAULT 'EXPECTED' NOT NULL,
    FILE_NAME          VARCHAR2(500)  NOT NULL,
    FILE_PATH          VARCHAR2(1000),
    STORAGE_LOCATION   VARCHAR2(200),
    FILE_SIZE_BYTES    NUMBER(20),
    CHECKSUM_ALGO      VARCHAR2(20),
    CHECKSUM_VALUE     VARCHAR2(200),
    VERIFIED_AT        TIMESTAMP,
    REMARKS            VARCHAR2(4000),
    CREATED_AT         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT         TIMESTAMP,
    CONSTRAINT PK_DATAPUMP_FILE
        PRIMARY KEY (DATAPUMP_FILE_ID),
    CONSTRAINT FK_DATAPUMP_FILE_RUN
        FOREIGN KEY (MIG_RUN_ID)
        REFERENCES MIGRATION_RUN (MIG_RUN_ID),
    CONSTRAINT FK_DATAPUMP_FILE_JOB
        FOREIGN KEY (DATAPUMP_JOB_ID)
        REFERENCES DATAPUMP_JOB (DATAPUMP_JOB_ID),
    CONSTRAINT CHK_DATAPUMP_FILE_ROLE
        CHECK (FILE_ROLE IN
               ('DUMP','EXPORT_LOG','IMPORT_LOG',
                'PARFILE','SQLFILE','CHECKSUM','MANIFEST')),
    CONSTRAINT CHK_DATAPUMP_FILE_STS
        CHECK (STATUS IN
               ('EXPECTED','CREATED','VERIFIED','CORRUPT','LOST'))
);

CREATE OR REPLACE TRIGGER TRG_DATAPUMP_FILE_BI
BEFORE INSERT ON DATAPUMP_FILE
FOR EACH ROW
BEGIN
    IF :NEW.DATAPUMP_FILE_ID IS NULL THEN
        SELECT SEQ_DATAPUMP_FILE.NEXTVAL
        INTO :NEW.DATAPUMP_FILE_ID FROM DUAL;
    END IF;
END;
/

-- ===========================================================================
-- 7. ARCHIVE_LOG（Archived Redo Log 論理台帳）FK→MIGRATION_RUN
-- ===========================================================================

CREATE SEQUENCE SEQ_ARCHIVE_LOG
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE ARCHIVE_LOG (
    ARCHIVE_LOG_ID        NUMBER(10)     NOT NULL,
    MIG_RUN_ID            NUMBER(10)     NOT NULL,
    SOURCE_DBID           NUMBER(20),
    SOURCE_RESETLOGS_ID   NUMBER(20)     NOT NULL,
    THREAD_NO             NUMBER(5)      NOT NULL,
    SEQUENCE_NO           NUMBER(20)     NOT NULL,
    FIRST_CHANGE_SCN      NUMBER(20),
    NEXT_CHANGE_SCN       NUMBER(20),
    FIRST_TIME            TIMESTAMP,
    NEXT_TIME             TIMESTAMP,
    DICTIONARY_BEGIN_FLAG CHAR(1)        DEFAULT 'N' NOT NULL,
    DICTIONARY_END_FLAG   CHAR(1)        DEFAULT 'N' NOT NULL,
    COLLECT_STATUS        VARCHAR2(20)   DEFAULT 'EXPECTED' NOT NULL,
    REMARKS               VARCHAR2(4000),
    CREATED_AT            TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT            TIMESTAMP,
    CONSTRAINT PK_ARCHIVE_LOG
        PRIMARY KEY (ARCHIVE_LOG_ID),
    CONSTRAINT FK_ARCHIVE_LOG_RUN
        FOREIGN KEY (MIG_RUN_ID)
        REFERENCES MIGRATION_RUN (MIG_RUN_ID),
    CONSTRAINT UQ_ARCHIVE_LOG_THREAD_SEQ
        UNIQUE (MIG_RUN_ID, SOURCE_RESETLOGS_ID,
                THREAD_NO, SEQUENCE_NO),
    CONSTRAINT CHK_ARCHIVE_LOG_COL_STS
        CHECK (COLLECT_STATUS IN
               ('EXPECTED','RECEIVED','VERIFIED',
                'CORRUPT','MISSING','IGNORED')),
    CONSTRAINT CHK_ARCHIVE_LOG_DICT_B
        CHECK (DICTIONARY_BEGIN_FLAG IN ('Y','N')),
    CONSTRAINT CHK_ARCHIVE_LOG_DICT_E
        CHECK (DICTIONARY_END_FLAG IN ('Y','N'))
);

CREATE OR REPLACE TRIGGER TRG_ARCHIVE_LOG_BI
BEFORE INSERT ON ARCHIVE_LOG
FOR EACH ROW
BEGIN
    IF :NEW.ARCHIVE_LOG_ID IS NULL THEN
        SELECT SEQ_ARCHIVE_LOG.NEXTVAL
        INTO :NEW.ARCHIVE_LOG_ID FROM DUAL;
    END IF;
END;
/

-- ===========================================================================
-- 8. ARCHIVE_LOG_COPY（Archived Redo Log 物理コピー管理テーブル）
--    FK→ARCHIVE_LOG, FK→MIGRATION_RUN
-- ===========================================================================

CREATE SEQUENCE SEQ_ARCHIVE_LOG_COPY
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE ARCHIVE_LOG_COPY (
    ARCHIVE_LOG_COPY_ID  NUMBER(10)     NOT NULL,
    ARCHIVE_LOG_ID       NUMBER(10)     NOT NULL,
    MIG_RUN_ID           NUMBER(10)     NOT NULL,
    STORAGE_LOCATION     VARCHAR2(200)  NOT NULL,
    FILE_PATH            VARCHAR2(1000) NOT NULL,
    FILE_SIZE_BYTES      NUMBER(20),
    CHECKSUM_ALGO        VARCHAR2(20),
    CHECKSUM_VALUE       VARCHAR2(200),
    COPY_STATUS          VARCHAR2(20)   DEFAULT 'EXPECTED' NOT NULL,
    RECEIVED_AT          TIMESTAMP,
    VERIFIED_AT          TIMESTAMP,
    REMARKS              VARCHAR2(4000),
    CREATED_AT           TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP,
    CONSTRAINT PK_ARCHIVE_LOG_COPY
        PRIMARY KEY (ARCHIVE_LOG_COPY_ID),
    CONSTRAINT FK_ARC_LOG_COPY_LOG
        FOREIGN KEY (ARCHIVE_LOG_ID)
        REFERENCES ARCHIVE_LOG (ARCHIVE_LOG_ID),
    CONSTRAINT FK_ARC_LOG_COPY_RUN
        FOREIGN KEY (MIG_RUN_ID)
        REFERENCES MIGRATION_RUN (MIG_RUN_ID),
    CONSTRAINT CHK_ARC_LOG_COPY_STS
        CHECK (COPY_STATUS IN
               ('EXPECTED','RECEIVED','VERIFIED',
                'REGISTERED','CORRUPT','LOST','DELETED'))
);

CREATE OR REPLACE TRIGGER TRG_ARCHIVE_LOG_COPY_BI
BEFORE INSERT ON ARCHIVE_LOG_COPY
FOR EACH ROW
BEGIN
    IF :NEW.ARCHIVE_LOG_COPY_ID IS NULL THEN
        SELECT SEQ_ARCHIVE_LOG_COPY.NEXTVAL
        INTO :NEW.ARCHIVE_LOG_COPY_ID FROM DUAL;
    END IF;
END;
/

-- ===========================================================================
-- 9. MIG_STATUS_HISTORY（状態変更監査履歴テーブル）FK→MIGRATION_RUN
-- INSERT専用（UPDATE・DELETE禁止）。PKG_MIG_ADMIN のAPI経由で管理する。
-- ===========================================================================

CREATE SEQUENCE SEQ_MIG_STATUS_HISTORY
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE MIG_STATUS_HISTORY (
    HISTORY_ID   NUMBER(10)     NOT NULL,
    MIG_RUN_ID   NUMBER(10)     NOT NULL,
    TABLE_NAME   VARCHAR2(100)  NOT NULL,
    RECORD_ID    NUMBER(20)     NOT NULL,
    OLD_STATUS   VARCHAR2(50),
    NEW_STATUS   VARCHAR2(50)   NOT NULL,
    CHANGED_BY   VARCHAR2(100)  NOT NULL,
    CHANGED_AT   TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    NOTE         VARCHAR2(4000),
    CONSTRAINT PK_MIG_STATUS_HISTORY
        PRIMARY KEY (HISTORY_ID),
    CONSTRAINT FK_MIG_STAT_HIST_RUN
        FOREIGN KEY (MIG_RUN_ID)
        REFERENCES MIGRATION_RUN (MIG_RUN_ID)
);

-- TRG_MIG_STATUS_HIST_BI: HISTORY_ID 採番のみ（CHANGED_AT は DEFAULT SYSTIMESTAMP）
CREATE OR REPLACE TRIGGER TRG_MIG_STATUS_HIST_BI
BEFORE INSERT ON MIG_STATUS_HISTORY
FOR EACH ROW
BEGIN
    IF :NEW.HISTORY_ID IS NULL THEN
        SELECT SEQ_MIG_STATUS_HISTORY.NEXTVAL
        INTO :NEW.HISTORY_ID FROM DUAL;
    END IF;
END;
/

EXIT;
