-- migration_ctl DDL v3.0 フェーズ1・2追加分
-- 実行ユーザー: migration_ctl
-- 実行対象: oracle-tgt (localhost:1521/XEPDB1)
-- 設計書: docs/migration-control-schema-design.md v3.0 §6.11〜§6.14
--
-- 前提: 02_migration_ctl_ddl.sql（9テーブル v2.0）が適用済みであること
-- 変更方式: 既存ファイル（02）を修正せず新規ファイルとして追加（§2.5参照）

WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR  EXIT FAILURE
SET ECHO ON FEEDBACK ON SERVEROUTPUT ON SIZE UNLIMITED

-- ===========================================================================
-- §6.14.1 DATAPUMP_FILE 列追加
-- ===========================================================================

-- 列追加（既存行は NULL が入る。後方互換あり）
ALTER TABLE DATAPUMP_FILE ADD (
    CONSUMED_BY_IMPORT_JOB_ID NUMBER(10),
    CONSUMED_AT               TIMESTAMP,
    TARGET_VERIFIED_AT        TIMESTAMP
);

-- FK 追加（CONSUMED_BY_IMPORT_JOB_ID → DATAPUMP_JOB）
ALTER TABLE DATAPUMP_FILE ADD CONSTRAINT FK_DP_FILE_CONSM_JOB
    FOREIGN KEY (CONSUMED_BY_IMPORT_JOB_ID)
    REFERENCES DATAPUMP_JOB (DATAPUMP_JOB_ID);

-- STATUS の CHECK 制約を再作成（CONSUMED 追加）
-- 開発環境・既存データ0件前提で DROP → ADD
ALTER TABLE DATAPUMP_FILE DROP CONSTRAINT CHK_DATAPUMP_FILE_STS;
ALTER TABLE DATAPUMP_FILE ADD CONSTRAINT CHK_DATAPUMP_FILE_STS
    CHECK (STATUS IN
           ('EXPECTED','CREATED','VERIFIED','CORRUPT','LOST','CONSUMED'));

-- ===========================================================================
-- §6.14.2 DATAPUMP_JOB 列追加
-- ===========================================================================

ALTER TABLE DATAPUMP_JOB ADD (
    REMAP_SCHEMA_DEF      VARCHAR2(500),
    REMAP_TABLESPACE_DEF  VARCHAR2(500),
    TABLE_EXISTS_ACTION   VARCHAR2(20),
    PARAMETER_TEXT        VARCHAR2(4000),
    RESULT_MESSAGE        VARCHAR2(4000)
);

-- TABLE_EXISTS_ACTION の CHECK 制約追加（NULL 許容）
ALTER TABLE DATAPUMP_JOB ADD CONSTRAINT CHK_DP_JOB_TEA
    CHECK (TABLE_EXISTS_ACTION IS NULL
           OR TABLE_EXISTS_ACTION IN ('SKIP','APPEND','TRUNCATE','REPLACE'));

-- ===========================================================================
-- §6.14.3 MIGRATION_OBJECT STATUS 拡張（IN_SCOPE / READY 追加）
-- ===========================================================================

ALTER TABLE MIGRATION_OBJECT DROP CONSTRAINT CHK_MIG_OBJ_STATUS;
ALTER TABLE MIGRATION_OBJECT ADD CONSTRAINT CHK_MIG_OBJ_STATUS
    CHECK (STATUS IN
           ('PENDING','IN_SCOPE','READY',
            'IN_PROGRESS','COMPLETED','FAILED','SKIPPED'));

-- ===========================================================================
-- §6.14.4 PHASE_STATUS 列追加
-- ===========================================================================

ALTER TABLE PHASE_STATUS ADD (
    APPROVAL_STATUS  VARCHAR2(20),
    APPROVED_BY      VARCHAR2(100),
    APPROVED_AT      TIMESTAMP
);

-- APPROVAL_STATUS の CHECK 制約追加（NULL 許容）
ALTER TABLE PHASE_STATUS ADD CONSTRAINT CHK_PHASE_APPR_STS
    CHECK (APPROVAL_STATUS IS NULL
           OR APPROVAL_STATUS IN ('PENDING','APPROVED','REJECTED'));

-- ===========================================================================
-- §6.11 ERROR_EVENT（エラーイベント台帳）
-- ===========================================================================

CREATE SEQUENCE SEQ_ERROR_EVENT
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE ERROR_EVENT (
    ERROR_EVENT_ID   NUMBER(10)     NOT NULL,
    MIG_RUN_ID       NUMBER(10)     NOT NULL,
    PHASE_CODE       VARCHAR2(20),
    SEVERITY         VARCHAR2(20)   NOT NULL,
    COMPONENT_NAME   VARCHAR2(100),
    DATAPUMP_JOB_ID  NUMBER(10),
    ORA_ERROR_CODE   VARCHAR2(20),
    ERROR_MESSAGE    VARCHAR2(4000),
    RESOLVE_STATUS   VARCHAR2(20)   DEFAULT 'OPEN' NOT NULL,
    RESOLVED_AT      TIMESTAMP,
    RESOLVE_NOTE     VARCHAR2(4000),
    CREATED_AT       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT       TIMESTAMP,
    CONSTRAINT PK_ERROR_EVENT
        PRIMARY KEY (ERROR_EVENT_ID),
    CONSTRAINT FK_ERROR_EVENT_RUN
        FOREIGN KEY (MIG_RUN_ID)
        REFERENCES MIGRATION_RUN (MIG_RUN_ID),
    CONSTRAINT FK_ERROR_EVENT_DP_JOB
        FOREIGN KEY (DATAPUMP_JOB_ID)
        REFERENCES DATAPUMP_JOB (DATAPUMP_JOB_ID),
    CONSTRAINT CHK_ERROR_EVENT_SEV
        CHECK (SEVERITY IN ('FATAL','ERROR','WARN')),
    CONSTRAINT CHK_ERROR_EVENT_RSTS
        CHECK (RESOLVE_STATUS IN ('OPEN','RESOLVED','IGNORED'))
);

CREATE OR REPLACE TRIGGER TRG_ERROR_EVENT_BI
BEFORE INSERT ON ERROR_EVENT
FOR EACH ROW
BEGIN
    IF :NEW.ERROR_EVENT_ID IS NULL THEN
        SELECT SEQ_ERROR_EVENT.NEXTVAL
        INTO :NEW.ERROR_EVENT_ID FROM DUAL;
    END IF;
END;
/

-- ===========================================================================
-- §6.12 VALIDATION_RUN（検証実行管理テーブル）
-- ===========================================================================

CREATE SEQUENCE SEQ_VALIDATION_RUN
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE VALIDATION_RUN (
    VALIDATION_RUN_ID  NUMBER(10)     NOT NULL,
    MIG_RUN_ID         NUMBER(10)     NOT NULL,
    PHASE_CODE         VARCHAR2(20)   NOT NULL,
    VALIDATION_TYPE    VARCHAR2(50)   NOT NULL,
    STATUS             VARCHAR2(20)   DEFAULT 'PLANNED' NOT NULL,
    OVERALL_RESULT     VARCHAR2(10),
    STARTED_AT         TIMESTAMP,
    FINISHED_AT        TIMESTAMP,
    REMARKS            VARCHAR2(4000),
    CREATED_AT         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT         TIMESTAMP,
    CONSTRAINT PK_VALIDATION_RUN
        PRIMARY KEY (VALIDATION_RUN_ID),
    CONSTRAINT FK_VALIDATION_RUN_RUN
        FOREIGN KEY (MIG_RUN_ID)
        REFERENCES MIGRATION_RUN (MIG_RUN_ID),
    CONSTRAINT CHK_VALID_RUN_TYPE
        CHECK (VALIDATION_TYPE IN
               ('ROW_COUNT','KEY_SET','AGGREGATE','LOB_HASH')),
    CONSTRAINT CHK_VALID_RUN_STATUS
        CHECK (STATUS IN
               ('PLANNED','RUNNING','COMPLETED','FAILED')),
    CONSTRAINT CHK_VALID_RUN_RESULT
        CHECK (OVERALL_RESULT IS NULL
               OR OVERALL_RESULT IN ('PASS','WARN','FAIL'))
);

CREATE OR REPLACE TRIGGER TRG_VALIDATION_RUN_BI
BEFORE INSERT ON VALIDATION_RUN
FOR EACH ROW
BEGIN
    IF :NEW.VALIDATION_RUN_ID IS NULL THEN
        SELECT SEQ_VALIDATION_RUN.NEXTVAL
        INTO :NEW.VALIDATION_RUN_ID FROM DUAL;
    END IF;
END;
/

-- ===========================================================================
-- §6.13 VALIDATION_RESULT（検証結果明細テーブル）
-- ===========================================================================

CREATE SEQUENCE SEQ_VALIDATION_RESULT
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE VALIDATION_RESULT (
    VALIDATION_RESULT_ID  NUMBER(10)     NOT NULL,
    VALIDATION_RUN_ID     NUMBER(10)     NOT NULL,
    MIG_OBJECT_ID         NUMBER(10),
    CHECK_NAME            VARCHAR2(100)  NOT NULL,
    EXPECTED_VALUE        VARCHAR2(4000),
    ACTUAL_VALUE          VARCHAR2(4000),
    RESULT                VARCHAR2(10)   NOT NULL,
    APPROVED_FLAG         CHAR(1)        DEFAULT 'N' NOT NULL,
    APPROVED_AT           TIMESTAMP,
    APPROVE_NOTE          VARCHAR2(4000),
    CREATED_AT            TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT            TIMESTAMP,
    CONSTRAINT PK_VALIDATION_RESULT
        PRIMARY KEY (VALIDATION_RESULT_ID),
    CONSTRAINT FK_VALID_RESULT_VRUN
        FOREIGN KEY (VALIDATION_RUN_ID)
        REFERENCES VALIDATION_RUN (VALIDATION_RUN_ID),
    CONSTRAINT FK_VALID_RESULT_OBJ
        FOREIGN KEY (MIG_OBJECT_ID)
        REFERENCES MIGRATION_OBJECT (MIG_OBJECT_ID),
    CONSTRAINT CHK_VALID_RESULT_RES
        CHECK (RESULT IN ('PASS','WARN','FAIL')),
    CONSTRAINT CHK_VALID_RESULT_APPR
        CHECK (APPROVED_FLAG IN ('Y','N'))
);

CREATE OR REPLACE TRIGGER TRG_VALIDATION_RESULT_BI
BEFORE INSERT ON VALIDATION_RESULT
FOR EACH ROW
BEGIN
    IF :NEW.VALIDATION_RESULT_ID IS NULL THEN
        SELECT SEQ_VALIDATION_RESULT.NEXTVAL
        INTO :NEW.VALIDATION_RESULT_ID FROM DUAL;
    END IF;
END;
/

EXIT;
