-- migration_ctl 追加DDL: MIG_CHECKPOINT（フェーズ3で採用・TMP-03 確定）
-- 実行ユーザー: migration_ctl
-- 実行対象: oracle-tgt (localhost:1522/XEPDB1)
--
-- 設計根拠: docs/phase3-design.md §3
--   設計メモ §5.2.4「Thread別チェックポイント」および §5.2.6「最終同期時に
--   MIG_CHECKPOINT が終了ログまで到達したことを確認する」がフェーズ3の完了条件のため採用。
--
-- 本番との差異: 本検証環境は oracle-src がシングルインスタンスのため THREAD_NO は常に 1。
--   本番（RAC）では Thread 数ぶんの行が作られ、COMPLETE_PHASE3 は全行を検査する。

WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR  EXIT FAILURE
SET ECHO ON
SET FEEDBACK ON

CREATE SEQUENCE SEQ_MIG_CHECKPOINT
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE MIG_CHECKPOINT (
    MIG_CHECKPOINT_ID  NUMBER(10)     NOT NULL,
    MIG_RUN_ID         NUMBER(10)     NOT NULL,
    COMPONENT_NAME     VARCHAR2(50)   NOT NULL,
    CHECKPOINT_KEY     VARCHAR2(100)  NOT NULL,
    THREAD_NO          NUMBER(5),
    SEQUENCE_NO        NUMBER(20),
    CHECKPOINT_SCN     NUMBER(20),
    REMARKS            VARCHAR2(4000),
    CREATED_AT         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT         TIMESTAMP,
    CONSTRAINT PK_MIG_CHECKPOINT
        PRIMARY KEY (MIG_CHECKPOINT_ID),
    CONSTRAINT FK_MIG_CHECKPOINT_RUN
        FOREIGN KEY (MIG_RUN_ID)
        REFERENCES MIGRATION_RUN (MIG_RUN_ID),
    CONSTRAINT UQ_MIG_CHECKPOINT_KEY
        UNIQUE (MIG_RUN_ID, COMPONENT_NAME, CHECKPOINT_KEY),
    CONSTRAINT CHK_MIG_CHECKPOINT_COMP
        CHECK (COMPONENT_NAME IN (
            'ARCHIVE_COLLECTOR', 'LOGMINER_READER', 'APPLY_WRITER'))
);

-- Oracle 12c 互換: IDENTITY 列を使わず SEQUENCE + BEFORE INSERT トリガーで採番する
CREATE OR REPLACE TRIGGER TRG_MIG_CHECKPOINT_BI
BEFORE INSERT ON MIG_CHECKPOINT
FOR EACH ROW
BEGIN
    IF :NEW.MIG_CHECKPOINT_ID IS NULL THEN
        SELECT SEQ_MIG_CHECKPOINT.NEXTVAL
        INTO :NEW.MIG_CHECKPOINT_ID FROM DUAL;
    END IF;
END;
/

PROMPT MIG_CHECKPOINT created.
EXIT;
