-- フェーズ4 管理テーブル DDL
-- 実行ユーザー: migration_ctl / 実行対象: oracle-tgt (localhost:1522/XEPDB1)
-- 設計: docs/phase4-design.md §3
-- Oracle 12c 互換: IDENTITY列禁止→SEQUENCE+トリガー採番、識別子30文字以内
-- 注意: 10_pkg_mig_admin_phase4.sql を先に依存するテーブルはないが、
--       MIGRATION_RUN / ARCHIVE_LOG / ERROR_EVENT への FK があるため
--       02_migration_ctl_ddl.sql / 04_phase1_2_additions.sql が先行適用済みであること

WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR  EXIT FAILURE
SET ECHO ON FEEDBACK ON SERVEROUTPUT ON SIZE UNLIMITED

-- ===========================================================================
-- LOGMINER_BATCH（解析範囲管理）
-- ===========================================================================

CREATE SEQUENCE SEQ_LOGMINER_BATCH
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE LOGMINER_BATCH (
    LOGMINER_BATCH_ID  NUMBER(10)     NOT NULL,
    MIG_RUN_ID         NUMBER(10)     NOT NULL,
    BATCH_NO           NUMBER(10)     NOT NULL,
    FROM_SCN           NUMBER(20)     NOT NULL,
    TO_SCN             NUMBER(20)     NOT NULL,
    DICT_METHOD        VARCHAR2(50)   NOT NULL,
    LOGMNR_OPTIONS     VARCHAR2(500),
    STATUS             VARCHAR2(20)   DEFAULT 'PLANNED' NOT NULL,
    CHANGE_COUNT       NUMBER(20),
    TRANSACTION_COUNT  NUMBER(20),
    STARTED_AT         TIMESTAMP,
    FINISHED_AT        TIMESTAMP,
    ERROR_MESSAGE      VARCHAR2(4000),
    REMARKS            VARCHAR2(4000),
    CREATED_AT         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT         TIMESTAMP,
    CONSTRAINT PK_LOGMINER_BATCH
        PRIMARY KEY (LOGMINER_BATCH_ID),
    CONSTRAINT FK_LOGMINER_BATCH_RUN
        FOREIGN KEY (MIG_RUN_ID)
        REFERENCES MIGRATION_RUN (MIG_RUN_ID),
    CONSTRAINT UQ_LOGMINER_BATCH_NO
        UNIQUE (MIG_RUN_ID, BATCH_NO),
    CONSTRAINT CHK_LOGMINER_BATCH_STS
        CHECK (STATUS IN
               ('PLANNED','RUNNING','COMPLETED','FAILED','RETRY')),
    CONSTRAINT CHK_LOGMINER_BATCH_DM
        CHECK (DICT_METHOD IN
               ('DICT_FROM_REDO_LOGS','DICT_FROM_ONLINE_CATALOG'))
);

CREATE OR REPLACE TRIGGER TRG_LOGMINER_BATCH_BI
BEFORE INSERT ON LOGMINER_BATCH
FOR EACH ROW
BEGIN
    IF :NEW.LOGMINER_BATCH_ID IS NULL THEN
        SELECT SEQ_LOGMINER_BATCH.NEXTVAL
        INTO :NEW.LOGMINER_BATCH_ID FROM DUAL;
    END IF;
END;
/

CREATE INDEX IDX_LOGMINER_BATCH_STS
    ON LOGMINER_BATCH (MIG_RUN_ID, STATUS);

CREATE INDEX IDX_LOGMINER_BATCH_SCN
    ON LOGMINER_BATCH (MIG_RUN_ID, FROM_SCN);

-- ===========================================================================
-- LOGMINER_BATCH_LOG（バッチ × Archived Redo 対応）
-- ===========================================================================

CREATE SEQUENCE SEQ_LOGMINER_BATCH_LOG
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE LOGMINER_BATCH_LOG (
    BATCH_LOG_ID        NUMBER(10)   NOT NULL,
    LOGMINER_BATCH_ID   NUMBER(10)   NOT NULL,
    ARCHIVE_LOG_ID      NUMBER(10)   NOT NULL,
    ADD_ORDER           NUMBER(5)    NOT NULL,
    CREATED_AT          TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_LOGMINER_BATCH_LOG
        PRIMARY KEY (BATCH_LOG_ID),
    CONSTRAINT FK_LOGMNR_BATCH_LOG_BATCH
        FOREIGN KEY (LOGMINER_BATCH_ID)
        REFERENCES LOGMINER_BATCH (LOGMINER_BATCH_ID),
    CONSTRAINT FK_LOGMNR_BATCH_LOG_ARC
        FOREIGN KEY (ARCHIVE_LOG_ID)
        REFERENCES ARCHIVE_LOG (ARCHIVE_LOG_ID),
    CONSTRAINT UQ_LOGMINER_BATCH_LOG
        UNIQUE (LOGMINER_BATCH_ID, ARCHIVE_LOG_ID)
);

CREATE OR REPLACE TRIGGER TRG_LOGMINER_BATCH_LOG_BI
BEFORE INSERT ON LOGMINER_BATCH_LOG
FOR EACH ROW
BEGIN
    IF :NEW.BATCH_LOG_ID IS NULL THEN
        SELECT SEQ_LOGMINER_BATCH_LOG.NEXTVAL
        INTO :NEW.BATCH_LOG_ID FROM DUAL;
    END IF;
END;
/

CREATE INDEX IDX_LOGMNR_BLOG_ORDER
    ON LOGMINER_BATCH_LOG (LOGMINER_BATCH_ID, ADD_ORDER);

CREATE INDEX IDX_LOGMNR_BLOG_ARC
    ON LOGMINER_BATCH_LOG (ARCHIVE_LOG_ID);

-- ===========================================================================
-- MINED_TRANSACTION（コミット済みトランザクション）
-- ===========================================================================

CREATE SEQUENCE SEQ_MINED_TRANSACTION
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE MINED_TRANSACTION (
    MINED_TRANSACTION_ID  NUMBER(10)    NOT NULL,
    MIG_RUN_ID            NUMBER(10)    NOT NULL,
    LOGMINER_BATCH_ID     NUMBER(10)    NOT NULL,
    XID                   VARCHAR2(50)  NOT NULL,
    START_SCN             NUMBER(20),
    COMMIT_SCN            NUMBER(20)    NOT NULL,
    STATUS                VARCHAR2(20)  DEFAULT 'MINED' NOT NULL,
    CHANGE_COUNT          NUMBER(20),
    CREATED_AT            TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT            TIMESTAMP,
    CONSTRAINT PK_MINED_TRANSACTION
        PRIMARY KEY (MINED_TRANSACTION_ID),
    CONSTRAINT FK_MINED_TX_RUN
        FOREIGN KEY (MIG_RUN_ID)
        REFERENCES MIGRATION_RUN (MIG_RUN_ID),
    CONSTRAINT FK_MINED_TX_BATCH
        FOREIGN KEY (LOGMINER_BATCH_ID)
        REFERENCES LOGMINER_BATCH (LOGMINER_BATCH_ID),
    CONSTRAINT UQ_MINED_TX_KEY
        UNIQUE (MIG_RUN_ID, XID, COMMIT_SCN),
    CONSTRAINT CHK_MINED_TX_STS
        CHECK (STATUS IN
               ('MINED','QUEUED','APPLIED','SKIPPED','ERROR'))
);

CREATE OR REPLACE TRIGGER TRG_MINED_TRANSACTION_BI
BEFORE INSERT ON MINED_TRANSACTION
FOR EACH ROW
BEGIN
    IF :NEW.MINED_TRANSACTION_ID IS NULL THEN
        SELECT SEQ_MINED_TRANSACTION.NEXTVAL
        INTO :NEW.MINED_TRANSACTION_ID FROM DUAL;
    END IF;
END;
/

CREATE INDEX IDX_MINED_TX_SCN
    ON MINED_TRANSACTION (MIG_RUN_ID, COMMIT_SCN, STATUS);

CREATE INDEX IDX_MINED_TX_BATCH
    ON MINED_TRANSACTION (LOGMINER_BATCH_ID, STATUS);

CREATE INDEX IDX_MINED_TX_STS
    ON MINED_TRANSACTION (MIG_RUN_ID, STATUS);

-- ===========================================================================
-- MINED_CHANGE（DML 明細）
-- ===========================================================================

CREATE SEQUENCE SEQ_MINED_CHANGE
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE MINED_CHANGE (
    MINED_CHANGE_ID       NUMBER(10)    NOT NULL,
    MIG_RUN_ID            NUMBER(10)    NOT NULL,
    MINED_TRANSACTION_ID  NUMBER(10)    NOT NULL,
    LOGMINER_BATCH_ID     NUMBER(10)    NOT NULL,
    RS_ID                 VARCHAR2(100) NOT NULL,
    SSN                   NUMBER(20)    NOT NULL,
    SCN                   NUMBER(20),
    COMMIT_SCN            NUMBER(20),
    OPERATION             VARCHAR2(20)  NOT NULL,
    SEG_OWNER             VARCHAR2(100),
    TABLE_NAME            VARCHAR2(100),
    CSF                   NUMBER(1)     DEFAULT 0 NOT NULL,
    SQL_REDO              CLOB,
    SQL_UNDO              CLOB,
    STATUS                VARCHAR2(20)  DEFAULT 'MINED' NOT NULL,
    CREATED_AT            TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT            TIMESTAMP,
    CONSTRAINT PK_MINED_CHANGE
        PRIMARY KEY (MINED_CHANGE_ID),
    CONSTRAINT FK_MINED_CHANGE_RUN
        FOREIGN KEY (MIG_RUN_ID)
        REFERENCES MIGRATION_RUN (MIG_RUN_ID),
    CONSTRAINT FK_MINED_CHANGE_TX
        FOREIGN KEY (MINED_TRANSACTION_ID)
        REFERENCES MINED_TRANSACTION (MINED_TRANSACTION_ID),
    CONSTRAINT FK_MINED_CHANGE_BATCH
        FOREIGN KEY (LOGMINER_BATCH_ID)
        REFERENCES LOGMINER_BATCH (LOGMINER_BATCH_ID),
    CONSTRAINT UQ_MINED_CHANGE_KEY
        UNIQUE (MIG_RUN_ID, RS_ID, SSN),
    CONSTRAINT CHK_MINED_CHANGE_OP
        CHECK (OPERATION IN
               ('INSERT','UPDATE','DELETE','COMMIT','ROLLBACK')),
    CONSTRAINT CHK_MINED_CHANGE_CSF
        CHECK (CSF IN (0, 1)),
    CONSTRAINT CHK_MINED_CHANGE_STS
        CHECK (STATUS IN
               ('MINED','QUEUED','APPLIED','SKIPPED','ERROR'))
);

CREATE OR REPLACE TRIGGER TRG_MINED_CHANGE_BI
BEFORE INSERT ON MINED_CHANGE
FOR EACH ROW
BEGIN
    IF :NEW.MINED_CHANGE_ID IS NULL THEN
        SELECT SEQ_MINED_CHANGE.NEXTVAL
        INTO :NEW.MINED_CHANGE_ID FROM DUAL;
    END IF;
END;
/

-- 4本の索引（大量行対応: docs/phase4-design.md §3.8 P4-08対応）
CREATE INDEX IDX_MINED_CHANGE_TX
    ON MINED_CHANGE (MINED_TRANSACTION_ID, SCN, RS_ID, SSN);

CREATE INDEX IDX_MINED_CHANGE_TBL
    ON MINED_CHANGE (MIG_RUN_ID, SEG_OWNER, TABLE_NAME, STATUS);

CREATE INDEX IDX_MINED_CHANGE_SCN
    ON MINED_CHANGE (MIG_RUN_ID, COMMIT_SCN, STATUS);

CREATE INDEX IDX_MINED_CHANGE_BST
    ON MINED_CHANGE (LOGMINER_BATCH_ID, STATUS);

-- ===========================================================================
-- APPLY_BATCH（差分適用範囲管理）
-- ===========================================================================

CREATE SEQUENCE SEQ_APPLY_BATCH
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE APPLY_BATCH (
    APPLY_BATCH_ID    NUMBER(10)     NOT NULL,
    MIG_RUN_ID        NUMBER(10)     NOT NULL,
    BATCH_NO          NUMBER(10)     NOT NULL,
    FROM_COMMIT_SCN   NUMBER(20)     NOT NULL,
    TO_COMMIT_SCN     NUMBER(20)     NOT NULL,
    STATUS            VARCHAR2(20)   DEFAULT 'PLANNED' NOT NULL,
    APPLIED_COUNT     NUMBER(20),
    SKIPPED_COUNT     NUMBER(20),
    ERROR_COUNT       NUMBER(20),
    STARTED_AT        TIMESTAMP,
    FINISHED_AT       TIMESTAMP,
    ERROR_MESSAGE     VARCHAR2(4000),
    REMARKS           VARCHAR2(4000),
    CREATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP,
    CONSTRAINT PK_APPLY_BATCH
        PRIMARY KEY (APPLY_BATCH_ID),
    CONSTRAINT FK_APPLY_BATCH_RUN
        FOREIGN KEY (MIG_RUN_ID)
        REFERENCES MIGRATION_RUN (MIG_RUN_ID),
    CONSTRAINT UQ_APPLY_BATCH_NO
        UNIQUE (MIG_RUN_ID, BATCH_NO),
    CONSTRAINT CHK_APPLY_BATCH_STS
        CHECK (STATUS IN
               ('PLANNED','RUNNING','COMPLETED','FAILED','RETRY'))
);

CREATE OR REPLACE TRIGGER TRG_APPLY_BATCH_BI
BEFORE INSERT ON APPLY_BATCH
FOR EACH ROW
BEGIN
    IF :NEW.APPLY_BATCH_ID IS NULL THEN
        SELECT SEQ_APPLY_BATCH.NEXTVAL
        INTO :NEW.APPLY_BATCH_ID FROM DUAL;
    END IF;
END;
/

CREATE INDEX IDX_APPLY_BATCH_STS
    ON APPLY_BATCH (MIG_RUN_ID, STATUS, FROM_COMMIT_SCN);

-- ===========================================================================
-- APPLY_TASK（DML 単位の適用・再処理キュー）
-- ===========================================================================

CREATE SEQUENCE SEQ_APPLY_TASK
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE APPLY_TASK (
    APPLY_TASK_ID     NUMBER(10)     NOT NULL,
    APPLY_BATCH_ID    NUMBER(10)     NOT NULL,
    MINED_CHANGE_ID   NUMBER(10)     NOT NULL,
    ERROR_EVENT_ID    NUMBER(10),
    MIG_RUN_ID        NUMBER(10)     NOT NULL,
    SEG_OWNER         VARCHAR2(100),
    TABLE_NAME        VARCHAR2(100),
    DML_TYPE          VARCHAR2(10)   NOT NULL,
    KEY_PAYLOAD       VARCHAR2(4000),
    DML_TEXT          VARCHAR2(4000),
    STATUS            VARCHAR2(20)   DEFAULT 'PENDING' NOT NULL,
    RETRY_COUNT       NUMBER(5)      DEFAULT 0 NOT NULL,
    EXECUTED_BY       VARCHAR2(100),
    STARTED_AT        TIMESTAMP,
    APPLIED_AT        TIMESTAMP,
    ERROR_MESSAGE     VARCHAR2(4000),
    CREATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP,
    CONSTRAINT PK_APPLY_TASK
        PRIMARY KEY (APPLY_TASK_ID),
    CONSTRAINT FK_APPLY_TASK_BATCH
        FOREIGN KEY (APPLY_BATCH_ID)
        REFERENCES APPLY_BATCH (APPLY_BATCH_ID),
    CONSTRAINT FK_APPLY_TASK_CHANGE
        FOREIGN KEY (MINED_CHANGE_ID)
        REFERENCES MINED_CHANGE (MINED_CHANGE_ID),
    CONSTRAINT FK_APPLY_TASK_ERR
        FOREIGN KEY (ERROR_EVENT_ID)
        REFERENCES ERROR_EVENT (ERROR_EVENT_ID),
    CONSTRAINT CHK_APPLY_TASK_STS
        CHECK (STATUS IN
               ('PENDING','RUNNING','APPLIED','RETRY','ERROR','SKIPPED')),
    CONSTRAINT CHK_APPLY_TASK_DML
        CHECK (DML_TYPE IN ('INSERT','UPDATE','DELETE'))
);

CREATE OR REPLACE TRIGGER TRG_APPLY_TASK_BI
BEFORE INSERT ON APPLY_TASK
FOR EACH ROW
BEGIN
    IF :NEW.APPLY_TASK_ID IS NULL THEN
        SELECT SEQ_APPLY_TASK.NEXTVAL
        INTO :NEW.APPLY_TASK_ID FROM DUAL;
    END IF;
END;
/

-- 3本の索引
CREATE INDEX IDX_APPLY_TASK_BATCH
    ON APPLY_TASK (APPLY_BATCH_ID, STATUS);

CREATE INDEX IDX_APPLY_TASK_CHANGE
    ON APPLY_TASK (MINED_CHANGE_ID);

CREATE INDEX IDX_APPLY_TASK_TBL
    ON APPLY_TASK (MIG_RUN_ID, SEG_OWNER, TABLE_NAME, STATUS);

-- ===========================================================================
-- ALTER TABLE ARCHIVE_LOG — MINING_STATUS / APPLY_STATUS 列追加
-- 設計: docs/phase4-design.md §3.7
-- 追加理由: フェーズ3 DDL 作成時点でフェーズ4設計が確定していなかったため後付け追加。
-- ===========================================================================

ALTER TABLE ARCHIVE_LOG ADD (
    MINING_STATUS  VARCHAR2(20),
    APPLY_STATUS   VARCHAR2(20)
);

-- CHECK 制約: NULL は許可（既存行はNULLで追加される）
-- CHK_ARCHIVE_LOG_MNSTS: 21文字 (Oracle 12c 識別子上限30文字以内)
ALTER TABLE ARCHIVE_LOG ADD CONSTRAINT CHK_ARCHIVE_LOG_MNSTS
    CHECK (MINING_STATUS IN ('PENDING','MINING','MINED','FAILED'));

-- CHK_ARCHIVE_LOG_APSTS: 21文字
ALTER TABLE ARCHIVE_LOG ADD CONSTRAINT CHK_ARCHIVE_LOG_APSTS
    CHECK (APPLY_STATUS IN ('PENDING','APPLIED','FAILED'));

PROMPT 09_phase4_tables.sql: completed successfully.

EXIT;
