-- Phase 2: 1.0スキーマ作成・権限設定
-- 実行場所: oracle-tgt コンテナ内
-- 接続: SYS as SYSDBA @ XEPDB1
-- 注意: STAGING_SCHEMA は setup.sh で既に作成済みのため、
--       ここでは追加権限のみ付与する

-- MIG_FS_DIR DIRECTORY 作成（oracle-tgt 側）
CREATE OR REPLACE DIRECTORY MIG_FS_DIR AS '/migfs';

-- STAGING_SCHEMA に READ/WRITE 権限付与
GRANT READ, WRITE ON DIRECTORY MIG_FS_DIR TO STAGING_SCHEMA;
GRANT READ, WRITE ON DIRECTORY MIG_FS_DIR TO SYSTEM;

-- Import 実行に必要な権限
GRANT DATAPUMP_IMP_FULL_DATABASE TO STAGING_SCHEMA;
GRANT CREATE SESSION TO STAGING_SCHEMA;
GRANT CREATE TABLE TO STAGING_SCHEMA;
GRANT CREATE INDEX TO STAGING_SCHEMA;
GRANT CREATE SEQUENCE TO STAGING_SCHEMA;
GRANT CREATE TRIGGER TO STAGING_SCHEMA;
GRANT UNLIMITED TABLESPACE TO STAGING_SCHEMA;

-- 確認クエリ
SELECT USERNAME, ACCOUNT_STATUS, DEFAULT_TABLESPACE
FROM DBA_USERS
WHERE USERNAME = 'STAGING_SCHEMA';

SELECT DIRECTORY_NAME, DIRECTORY_PATH
FROM DBA_DIRECTORIES
WHERE DIRECTORY_NAME = 'MIG_FS_DIR';

-- 本番では別途確認が必要な項目:
-- - 表領域 QUOTA の適切な設定
-- - LOB セグメントの配置先表領域
