-- Phase 2: Import 権限確認
-- 実行場所: oracle-tgt コンテナ内
-- 接続: SYS as SYSDBA @ XEPDB1

-- STAGING_SCHEMA のロール権限確認
SELECT GRANTED_ROLE
FROM DBA_ROLE_PRIVS
WHERE GRANTEE = 'STAGING_SCHEMA'
ORDER BY GRANTED_ROLE;

-- STAGING_SCHEMA のシステム権限確認
SELECT PRIVILEGE
FROM DBA_SYS_PRIVS
WHERE GRANTEE = 'STAGING_SCHEMA'
ORDER BY PRIVILEGE;

-- MIG_FS_DIR のオブジェクト権限確認
SELECT TABLE_NAME, PRIVILEGE
FROM ALL_TAB_PRIVS
WHERE GRANTEE = 'STAGING_SCHEMA'
  AND TABLE_NAME = 'MIG_FS_DIR'
ORDER BY PRIVILEGE;

-- DIRECTORY 存在確認
SELECT DIRECTORY_NAME, DIRECTORY_PATH
FROM DBA_DIRECTORIES
WHERE DIRECTORY_NAME = 'MIG_FS_DIR';

-- 本番では別途確認が必要な項目:
-- - DATAPUMP_IMP_FULL_DATABASE ロールが付与されているか
-- - 表領域 QUOTA が十分か（UNLIMITED TABLESPACE が不可の場合は個別設定）
