-- Phase 2: DDL プレビュー確認
-- 実行場所: oracle-tgt コンテナ内（SQLFILE 生成後）
-- 接続: MIGRATION_CTL @ XEPDB1
-- このSQLは管理テーブルでの記録確認用

-- SQLFILE ジョブの状態確認
SELECT DATAPUMP_JOB_ID, JOB_NAME, OPERATION, STATUS, RESULT_MESSAGE
FROM DATAPUMP_JOB
WHERE OPERATION = 'SQLFILE'
ORDER BY CREATED_AT DESC;

-- 生成されたSQLFILE の登録確認
SELECT FILE_NAME, FILE_SIZE_BYTES, STATUS, CHECKSUM_VALUE
FROM DATAPUMP_FILE
WHERE FILE_ROLE = 'SQLFILE'
ORDER BY CREATED_AT DESC;

-- PHASE_STATUS の承認状態確認
SELECT PHASE_CODE, STATUS, APPROVAL_STATUS, APPROVED_BY, APPROVED_AT
FROM PHASE_STATUS
WHERE PHASE_CODE = 'PHASE2'
ORDER BY MIG_RUN_ID DESC;
