-- Phase 2: impdp 実行中監視
-- 実行場所: oracle-tgt コンテナ内
-- 接続: SYS as SYSDBA @ XEPDB1

-- 実行中の Data Pump ジョブ一覧
SELECT JOB_NAME, OPERATION, JOB_MODE, STATE, DEGREE, ATTACHED_SESSIONS
FROM DBA_DATAPUMP_JOBS
WHERE STATE != 'NOT RUNNING'
ORDER BY JOB_NAME;

-- 進捗状況（V$SESSION_LONGOPS 結合）
SELECT
    j.JOB_NAME,
    s.OPNAME,
    s.SOFAR,
    s.TOTALWORK,
    ROUND(s.SOFAR / NULLIF(s.TOTALWORK, 0) * 100, 1) AS PCT_COMPLETE,
    s.TIME_REMAINING
FROM DBA_DATAPUMP_JOBS j
JOIN V$SESSION_LONGOPS s
    ON s.OPNAME LIKE '%' || j.JOB_NAME || '%'
WHERE j.STATE != 'NOT RUNNING';

-- 管理テーブルのジョブ状態確認（MIGRATION_CTL 接続時）
-- SELECT DATAPUMP_JOB_ID, JOB_NAME, OPERATION, STATUS, STARTED_AT, FINISHED_AT
-- FROM DATAPUMP_JOB
-- WHERE OPERATION = 'IMPORT'
-- ORDER BY CREATED_AT DESC;
