-- Phase 2: 索引・外部キー制約の再構築
-- 実行場所: oracle-tgt / SYSDBA（ALTER SESSION SET CONTAINER=XEPDB1 が必要）
-- 注意: SYSDBA 接続時は USER=SYS のため USER_CONSTRAINTS/USER_INDEXES は SYS のオブジェクトを参照する。
--       STAGING_SCHEMA のオブジェクトを参照するには DBA_CONSTRAINTS/DBA_INDEXES に OWNER='STAGING_SCHEMA'
--       を指定すること。
-- 本番では別途確認が必要な項目:
--   外部キー制約の正確な定義は移行元 DBA_CONSTRAINTS から取得すること
--   インデックス定義（降順・関数ベース等）は DDL を直接参照すること

SET SERVEROUTPUT ON

-- REGIONS の自己参照FK再作成
-- （Import 時に EXCLUDE=INDEX を指定したため FK も除外されている可能性あり）
DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_cnt
    FROM DBA_CONSTRAINTS
    WHERE OWNER = 'STAGING_SCHEMA'
      AND TABLE_NAME = 'REGIONS'
      AND CONSTRAINT_NAME = 'FK_REGIONS_PARENT';

    IF v_cnt = 0 THEN
        -- 自己参照FKが移行元に存在する場合のみ実行
        -- 移行元の定義を確認してから適用すること
        -- EXECUTE IMMEDIATE '
        --     ALTER TABLE STAGING_SCHEMA.REGIONS ADD CONSTRAINT FK_REGIONS_PARENT
        --     FOREIGN KEY (PARENT_REGION_ID) REFERENCES STAGING_SCHEMA.REGIONS(REGION_ID)';
        DBMS_OUTPUT.PUT_LINE('FK_REGIONS_PARENT: 未設定（移行元の定義を確認後に実行してください）');
    ELSE
        DBMS_OUTPUT.PUT_LINE('FK_REGIONS_PARENT: 既存');
    END IF;
END;
/

-- 索引の現在状態確認
SELECT INDEX_NAME, TABLE_NAME, INDEX_TYPE, STATUS
FROM DBA_INDEXES
WHERE OWNER = 'STAGING_SCHEMA'
  AND TABLE_NAME IN ('REGIONS', 'CUSTOMERS', 'ORDERS')
ORDER BY TABLE_NAME, INDEX_NAME;

-- 制約の現在状態確認
SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS
FROM DBA_CONSTRAINTS
WHERE OWNER = 'STAGING_SCHEMA'
  AND TABLE_NAME IN ('REGIONS', 'CUSTOMERS', 'ORDERS')
  AND CONSTRAINT_TYPE IN ('P', 'U', 'R', 'C')
ORDER BY TABLE_NAME, CONSTRAINT_TYPE, CONSTRAINT_NAME;
