-- Phase 2: 移行元（SRC_SCHEMA）の検証値取得
-- 実行場所: oracle-src コンテナ内（SYSDBA 接続 + ALTER SESSION SET CONTAINER=XEPDB1）
-- 注意: データジェネレータが稼働中の場合、現在件数は Export 時より多い
--       AS OF SCN を使用して基準SCN断面の件数を取得すること
-- 使い方: BASELINE_SCN を :scn にバインドして実行
-- 本番では別途確認が必要な項目:
--   BLOB/CLOB のハッシュ比較（今回の対象テーブルにはLOBなし）
--   UNDO_RETENTION が短い場合は AS OF SCN 取得が失敗する可能性あり

-- 件数確認（AS OF SCN を使用）
-- ※ :scn に BASELINE_SCN の値を設定すること
SELECT 'SRC_SCHEMA' AS SCHEMA_NAME, 'REGIONS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM SRC_SCHEMA.REGIONS AS OF SCN :scn
UNION ALL
SELECT 'SRC_SCHEMA', 'CUSTOMERS', COUNT(*) FROM SRC_SCHEMA.CUSTOMERS AS OF SCN :scn
UNION ALL
SELECT 'SRC_SCHEMA', 'ORDERS', COUNT(*) FROM SRC_SCHEMA.ORDERS AS OF SCN :scn;

-- 現在件数との比較（参考）
-- 以下は Export 後に追加された差分行数を確認する場合に使用
-- SELECT 'REGIONS' AS TABLE_NAME, COUNT(*) AS CURRENT_COUNT FROM SRC_SCHEMA.REGIONS
-- UNION ALL
-- SELECT 'CUSTOMERS', COUNT(*) FROM SRC_SCHEMA.CUSTOMERS
-- UNION ALL
-- SELECT 'ORDERS', COUNT(*) FROM SRC_SCHEMA.ORDERS;

-- キー集合の確認（チェックサム的な集計）
SELECT
    'REGIONS' AS TABLE_NAME,
    SUM(REGION_ID) AS KEY_SUM,
    MIN(REGION_ID) AS KEY_MIN,
    MAX(REGION_ID) AS KEY_MAX,
    COUNT(*) AS ROW_COUNT
FROM SRC_SCHEMA.REGIONS
UNION ALL
SELECT
    'CUSTOMERS',
    SUM(CUSTOMER_ID),
    MIN(CUSTOMER_ID),
    MAX(CUSTOMER_ID),
    COUNT(*)
FROM SRC_SCHEMA.CUSTOMERS
UNION ALL
SELECT
    'ORDERS',
    SUM(ORDER_ID),
    MIN(ORDER_ID),
    MAX(ORDER_ID),
    COUNT(*)
FROM SRC_SCHEMA.ORDERS;
