-- Phase 2: 移行先（STAGING_SCHEMA）の検証値取得と突合
-- 実行場所: oracle-tgt コンテナ内
-- 接続: STAGING_SCHEMA または SYSDBA

-- 件数確認
SELECT 'STAGING_SCHEMA' AS SCHEMA_NAME, 'REGIONS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM STAGING_SCHEMA.REGIONS
UNION ALL
SELECT 'STAGING_SCHEMA', 'CUSTOMERS', COUNT(*) FROM STAGING_SCHEMA.CUSTOMERS
UNION ALL
SELECT 'STAGING_SCHEMA', 'ORDERS', COUNT(*) FROM STAGING_SCHEMA.ORDERS;

-- キー集合チェック（移行元と比較する）
SELECT
    'REGIONS' AS TABLE_NAME,
    SUM(REGION_ID) AS KEY_SUM,
    MIN(REGION_ID) AS KEY_MIN,
    MAX(REGION_ID) AS KEY_MAX,
    COUNT(*) AS ROW_COUNT
FROM STAGING_SCHEMA.REGIONS
UNION ALL
SELECT
    'CUSTOMERS',
    SUM(CUSTOMER_ID),
    MIN(CUSTOMER_ID),
    MAX(CUSTOMER_ID),
    COUNT(*)
FROM STAGING_SCHEMA.CUSTOMERS
UNION ALL
SELECT
    'ORDERS',
    SUM(ORDER_ID),
    MIN(ORDER_ID),
    MAX(ORDER_ID),
    COUNT(*)
FROM STAGING_SCHEMA.ORDERS;
