-- Phase 2: 再Import 初期化（失敗時のリトライ用）
-- 実行場所: oracle-tgt / SYSDBA
-- 警告: このSQLを実行するとSTAGING_SCHEMAのデータが削除されます
-- 実行前に MIG_RUN_ID を :run_id にバインドして実行すること

WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR  EXIT FAILURE
SET SERVEROUTPUT ON

-- 対象テーブルのデータ削除（外部キー依存順に TRUNCATE）
BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE STAGING_SCHEMA.ORDERS';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE STAGING_SCHEMA.CUSTOMERS';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE STAGING_SCHEMA.REGIONS';
    DBMS_OUTPUT.PUT_LINE('STAGING_SCHEMA テーブルを初期化しました');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('エラー: ' || SQLERRM);
        RAISE;
END;
/

-- 管理テーブルの IMPORT ジョブを RETRY 状態へ
UPDATE DATAPUMP_JOB
SET STATUS     = 'RETRY',
    UPDATED_AT = SYSTIMESTAMP
WHERE MIG_RUN_ID = :run_id
  AND OPERATION  = 'IMPORT'
  AND STATUS IN ('FAILED', 'COMPLETED');

-- DATAPUMP_FILE の CONSUMED を VERIFIED に戻す（再Import可能にする）
UPDATE DATAPUMP_FILE
SET STATUS                    = 'VERIFIED',
    CONSUMED_AT               = NULL,
    CONSUMED_BY_IMPORT_JOB_ID = NULL,
    TARGET_VERIFIED_AT        = NULL,
    UPDATED_AT                = SYSTIMESTAMP
WHERE MIG_RUN_ID = :run_id
  AND FILE_ROLE  = 'DUMP'
  AND STATUS     = 'CONSUMED';

-- PHASE_STATUS を PAUSED へ
UPDATE PHASE_STATUS
SET STATUS     = 'PAUSED',
    UPDATED_AT = SYSTIMESTAMP
WHERE MIG_RUN_ID = :run_id
  AND PHASE_CODE = 'PHASE2';

-- ERROR_EVENT の解消
UPDATE ERROR_EVENT
SET RESOLVE_STATUS = 'RESOLVED',
    RESOLVED_AT    = SYSTIMESTAMP,
    RESOLVE_NOTE   = '再Import実行のため手動解消',
    UPDATED_AT     = SYSTIMESTAMP
WHERE MIG_RUN_ID   = :run_id
  AND PHASE_CODE   = 'PHASE2'
  AND RESOLVE_STATUS = 'OPEN';

-- VALIDATION_RESULT の削除（前回実行の FAIL 結果が COMPLETE_PHASE 条件5を阻害するため）
-- VALIDATION_RESULT → VALIDATION_RUN の順で削除（FK制約順）
DELETE FROM VALIDATION_RESULT
WHERE VALIDATION_RUN_ID IN (
    SELECT VALIDATION_RUN_ID
    FROM VALIDATION_RUN
    WHERE MIG_RUN_ID  = :run_id
      AND PHASE_CODE  = 'PHASE2'
);

-- VALIDATION_RUN の削除
DELETE FROM VALIDATION_RUN
WHERE MIG_RUN_ID = :run_id
  AND PHASE_CODE = 'PHASE2';

COMMIT;

BEGIN
    DBMS_OUTPUT.PUT_LINE('再Import用初期化が完了しました。RUN_ID=' || :run_id);
    DBMS_OUTPUT.PUT_LINE('  - STAGING_SCHEMA テーブル: TRUNCATE 済み');
    DBMS_OUTPUT.PUT_LINE('  - DATAPUMP_JOB: RETRY 状態へ遷移');
    DBMS_OUTPUT.PUT_LINE('  - DATAPUMP_FILE (DUMP): VERIFIED 状態へ戻し');
    DBMS_OUTPUT.PUT_LINE('  - PHASE_STATUS (PHASE2): PAUSED へ遷移');
    DBMS_OUTPUT.PUT_LINE('  - ERROR_EVENT (PHASE2): RESOLVED へ解消');
    DBMS_OUTPUT.PUT_LINE('  - VALIDATION_RUN/RESULT (PHASE2): 削除済み');
END;
/
