-- Oracle 21c XE (CDB/PDB) では XEPDB1 (PDB) に接続してユーザーを作成する。
-- 本番 Oracle 12c non-CDB の場合は CONNECT 先のサービス名を調整すること。

WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR  EXIT FAILURE
SET ECHO ON
SET FEEDBACK ON
SET SERVEROUTPUT ON SIZE UNLIMITED

PROMPT ============================================================
PROMPT Creating application schemas
PROMPT   ORACLE_HOST    : &&ORACLE_HOST
PROMPT   ORACLE_PORT    : &&ORACLE_PORT
PROMPT   ORACLE_SERVICE : &&ORACLE_SERVICE
PROMPT ============================================================

CONNECT sys/&&ORACLE_PASSWORD@//&&ORACLE_HOST:&&ORACLE_PORT/&&ORACLE_SERVICE AS SYSDBA

PROMPT Creating LOG_SCHEMA...
CREATE USER log_schema IDENTIFIED BY &&LOG_SCHEMA_PASS;
GRANT CONNECT TO log_schema;
GRANT RESOURCE TO log_schema;
GRANT CREATE TABLE TO log_schema;
GRANT CREATE SEQUENCE TO log_schema;
GRANT CREATE TRIGGER TO log_schema;
GRANT CREATE PROCEDURE TO log_schema;
ALTER USER log_schema QUOTA UNLIMITED ON USERS;

PROMPT Creating SRC_SCHEMA...
CREATE USER src_schema IDENTIFIED BY &&SRC_SCHEMA_PASS;
GRANT CONNECT TO src_schema;
GRANT RESOURCE TO src_schema;
ALTER USER src_schema QUOTA UNLIMITED ON USERS;

PROMPT Creating TGT_SCHEMA...
CREATE USER tgt_schema IDENTIFIED BY &&TGT_SCHEMA_PASS;
GRANT CONNECT TO tgt_schema;
GRANT RESOURCE TO tgt_schema;
ALTER USER tgt_schema QUOTA UNLIMITED ON USERS;

PROMPT Users created.
EXIT;
